exec(open("src_background/analytical.py").read())

#Plotting the plot for eta(x), t(x), equality times, and beginning of acceleration
plt.figure(figsize = (16,8))
plt.plot(x, t_of_x_scaled, label = "Time t(x)")
plt.plot(x, (eta_of_x_scaled), label = "Conformal time $\eta(x)/c$")
plt.plot(x_scale_rad,t_R, label = "Radiation dominated era $t$", linestyle = "dashed")
plt.plot(x_scale_mat,t_M, label = "Matter dominated era $t$", linestyle = "dashed")
plt.plot(x_scale_lam, t_Lambda, label = "Dark energy dominated era $t$", linestyle = "dashed")
plt.plot(x_scale_rad, eta_R, label = "Radiation dominaed era $\\eta$", linestyle = "dashed")
plt.plot(x_scale_mat, eta_M, label = "Matter dominated era $\\eta$", linestyle = "dashed")
plt.plot(x_scale_lam, eta_Lambda, label = "Dark energy dominated era $\\eta$", linestyle = "dashed")
plt.vlines(x = matter_radiation_eq, ymin = 0, ymax = 10**13, color = "#ff69d4", linestyle = "dotted", label = "Matter - radiation \n equality")
plt.vlines(x = matter_dark_energy_eq, ymin = 0, ymax = 10**13, color = "#50c878", linestyle = "dotted", label = "Matter - radiation \n equality")
plt.vlines(x = acceleration, ymin = 0, ymax = 10**13,color = "#45b6fe", linestyle = "dotted", label = "Acceleration begins")
plt.axvline(x = matter_radiation_eq_eta, linestyle=(0, (2, 2)), color = "#545454", label = "Reionisation ($z=7.8$)")

# plt.vlines(x = 0, ymin = 0, ymax = 10**13, color = "#8a00c4", linestyle = "dotted", label = "Today")
# plt.axhline(y = 65378.8413334679, color = 'r', linestyle = '-')
# plt.axhline(y = 11781394967.125027, color = 'r', linestyle = '-')
# plt.axhline(y = 444734600.9098152, color = 'r', linestyle = '-')
# plt.axhline(y = 45203002534.52784, color = 'r', linestyle = '-')
plt.xlabel("x", fontsize = 15)
plt.ylabel("Time in years", fontsize = 15)
plt.xlim(-14,5)
plt.ylim(10**-0.5, 10**13)
plt.yscale("log")
plt.legend(fontsize = "12")
# plt.savefig("plots/equality_times.pdf")
plt.show()